ALTER TABLE export_tasks
  ADD COLUMN user_id VARCHAR(64) NULL,
  ADD COLUMN company_uuid VARCHAR(64) NULL,
  ADD COLUMN request_id VARCHAR(128) NULL,
  ADD COLUMN file_name VARCHAR(255) NULL,
  ADD COLUMN file_size BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN oss_key VARCHAR(1024) NULL,
  ADD COLUMN oss_url TEXT NULL,
  ADD COLUMN oss_status VARCHAR(32) NULL,
  ADD COLUMN oss_error TEXT NULL,
  ADD COLUMN expired_at DATETIME(6) NULL,
  ADD COLUMN callback_url VARCHAR(1024) NULL,
  ADD COLUMN callback_status VARCHAR(32) NULL,
  ADD COLUMN callback_error TEXT NULL,
  ADD COLUMN callback_retry_count INT NOT NULL DEFAULT 0,
  ADD COLUMN source_system VARCHAR(64) NULL,
  ADD KEY idx_export_tasks_user_created_at (user_id, created_at),
  ADD KEY idx_export_tasks_request_id (request_id),
  ADD KEY idx_export_tasks_callback_status_updated_at (callback_status, updated_at);
